'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class billingactivity
    
    '''<summary>
    '''cboPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPeriod As Global.Telerik.Web.UI.RadDropDownList
    
    '''<summary>
    '''RadDatePickerFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerFrom As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePickerTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerTo As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''cboEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEmployee As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''hour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hour As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''day control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents day As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''week control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents week As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''weekday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents weekday As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''month control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents month As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''quarter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quarter As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents year As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadChartRemainderStadistic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadChartRemainderStadistic As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''SqlDataSourceRemainderStadistic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRemainderStadistic As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceEmpl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceEmpl As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblDatePart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDatePart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEmployeeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCompanyId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As pasconcept20.ADM_Main_Responsive
        Get
            Return CType(MyBase.Master,pasconcept20.ADM_Main_Responsive)
        End Get
    End Property
End Class
