'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class employees_sync_qb

    '''<summary>
    '''ConnectPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConnectPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnDisconnectFromQuickBooks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDisconnectFromQuickBooks As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnConnectToQuickBooks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConnectToQuickBooks As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnGetVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetVendors As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SyncPanelVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SyncPanelVendors As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnBulkLinkVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBulkLinkVendors As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnBulkCopyVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBulkCopyVendors As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''RadGridVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridVendors As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadGridLinkedVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridLinkedVendors As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadToolTipSearchVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipSearchVendors As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''pnlFindVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFindVendors As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtFindVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFindVendors As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnFindVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFindVendors As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''RadGridSearhcVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridSearhcVendors As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''SqlDataSourceVendorsPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceVendorsPending As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceQBLinkedVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceQBLinkedVendors As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceQBNotLinkedVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceQBNotLinkedVendors As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblCompanyId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectVendors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectVendors As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As pasconcept20.ADM_Main_Responsive
        Get
            Return CType(MyBase.Master, pasconcept20.ADM_Main_Responsive)
        End Get
    End Property
End Class
