'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class rfps
    
    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''btnTablePage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTablePage As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNew As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFind As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cboPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPeriod As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''RadDatePickerFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerFrom As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''RadDatePickerTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDatePickerTo As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''cboSubconsultant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSubconsultant As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''cboStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboStatus As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''cboDiscipline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDiscipline As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''txtFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFind As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''RadTreeList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadTreeList1 As Global.Telerik.Web.UI.RadTreeList
    
    '''<summary>
    '''RadToolTipAccept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipAccept As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''lblRFPNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRFPNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboJob As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''chkNotifyAccept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNotifyAccept As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''btnAcceptConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAcceptConfirm As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Comparevalidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Comparevalidator1 As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''RadToolTipDecline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipDecline As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''txtDeclineNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeclineNotes As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''chkNotifyDecline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNotifyDecline As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''btnDeclineConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeclineConfirm As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''RadToolTipNewRFPforProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolTipNewRFPforProject As Global.Telerik.Web.UI.RadToolTip
    
    '''<summary>
    '''lblProjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboSubconsultantNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSubconsultantNew As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Comparevalidator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Comparevalidator5 As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''btnInsertRFPforProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInsertRFPforProject As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''SqlDataSourceSubconsultant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSubconsultant As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceRFP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRFP As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceMonths As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceYears As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceDiscipline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceDiscipline As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceStatus As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceRFPdetalles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRFPdetalles As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceTandCtemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceTandCtemplates As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourcePaymentSchedules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourcePaymentSchedules As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceJob As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceAzureFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAzureFiles As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblGuiId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGuiId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCompanyId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRFPSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRFPSelected As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As pasconcept20.ADM_Main_Responsive
        Get
            Return CType(MyBase.Master,pasconcept20.ADM_Main_Responsive)
        End Get
    End Property
End Class
