'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class company1

    '''<summary>
    '''RadToolBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadToolBar1 As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnSentContactAgain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSentContactAgain As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblGetStartedEmailDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGetStartedEmailDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FormView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormView1 As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''RadGridImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridImg As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''SqlDataSourceImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceImages As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceTypes As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceBillingPlas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceBillingPlas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceUserByCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceUserByCompany As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSourceVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceVersion As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblMasterMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterMail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCompanyId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As pasconcept20.MasterPage
        Get
            Return CType(MyBase.Master, pasconcept20.MasterPage)
        End Get
    End Property
End Class
