'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompanyPendingBills

    '''<summary>
    '''cboStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboStatus As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadGridPayments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridPayments As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''SqlDataSourcePayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourcePayment As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As pasconcept20.MasterPage
        Get
            Return CType(MyBase.Master, pasconcept20.MasterPage)
        End Get
    End Property
End Class
